### PR TITLE
Reportmapintegration

### PR DESCRIPTION
**Pull request by MaanasaPriyaa**
1. Fixed /reports/confirmed API to return GeoJSON
2. Fixed mapcode to use this instead of mock data
3. Mayank fixed incorrect location pick bug

### CODE REVIEW

**Comment by talltom** [comment]
Hi, just need to grap some server credentials from you guys to test this (see email).

**Comment by talltom** [comment]
Also, it looks like we might still be hard coding an image input: https://github.com/urbanriskmap/cognicity-grasp/blob/reportmapintegration/ReportCard.js#L405

**Comment by MaanasaPriyaa** [comment]
Responded to first comment in email.
As for the second, we are not hardcoding image input. Image_id needs to be unique and setting the card_id value for it makes sense. But image_id is of the type big int. That needs to be updated in schema if we go ahead with this idea. If we are retaining it as an integer, we need to decide what value will be set for it.

**Comment by talltom** [comment]
Thanks @MaanasaPriyaa - in that case, perhaps we should just make a generic primary key on the images table which is completed by the database, and then we are only required to send the following data to the images table:
- card_id
- filename
- url_path

If you think that works I can make the change in the schema, and you could change the grasp code?

**Comment by MaanasaPriyaa** [comment]
@talltom done. grasp_report_images has no image_id now. It returns pkey on insert which gets set as image_id in the grasp_reports table. Corresponding DB test is updated as well.

**Comment by abrahamq** [comment]
We need to change the getSigned call to AWS to use image_id as the url instead of card_id.

**Pull request merged**
